name: cicd

on:
  push:
    branches: 
       - OS_UI-Dev
env:
  AWS_REGION: us-east-1
  
jobs:
  build-and-deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ui-plugins/auth/package-lock.json
      
      - name: Install dependencies
        working-directory: ./auth
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
     
      - name: Create application bundle (zip)
        run: |
          zip -r eb-deploy-${{ github.sha }}.zip . -x "*.git*" "node_modules/*" ":/tmp/*" ".github/*"
    
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          application_name: 'OS_DevOpsLab'
          environment_name: 'OS_DevOpsLab-env'
          version_label: ${{ github.sha }}
          region: ${{ env.AWS_REGION }}
          deployment_package: eb-deploy-${{ github.sha }}.zip
